version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./app
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: fullcycle
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  db-data:
